using DataAccessLayer;
using Project.APi.ToolDummyData;
using System.Threading.Tasks;
using System.Web.Http;

namespace Project.APi.Controllers
{
    [RoutePrefix("api/dummydata")]
    public class DummyDataController : ApiController
    {
        [HttpPost]
        public async Task<IHttpActionResult> Gennerate([FromBody]int total)
        {
            AutoGenerateData auto = new AutoGenerateData(new EfDbContext());
            System.Collections.Generic.List<System.Guid> lCate = auto.GennerateCategory();
            for (int i = 0; i < total; i++)
            {
                auto.GennerateCountry();
                auto.GennerateProduct(lCate);
            }
            int result = await auto.SaveChangeAsync();
            var Output = new
            {
                Success = (result > 0),
                Total = result
            };
            return Json(Output);
        }

        [HttpPost]
        [Route("user")]
        public async Task<IHttpActionResult> GennerateUser([FromBody] int total)
        {
            AutoGenerateData auto = new AutoGenerateData(new EfDbContext());
            var list = await auto.GetAllIdCountry();
            for (int i = 0; i < total; i++)
            {
               await auto.GennerateUser(list);
            }
            return StatusCode(System.Net.HttpStatusCode.OK);
        }
    }
}