using DataAccessLayer;
using Project.APi.ToolDummyData;
using System.Threading.Tasks;
using System.Web.Http;

namespace Project.APi.Controllers
{
    public class DummyDataController : ApiController
    {
        [HttpPost]
        public async Task<IHttpActionResult> Gennerate([FromBody]int total)
        {
            AutoGenerateData auto = new AutoGenerateData(new EfDbContext());
            var lCate = auto.GennerateCategory();
            for (int i = 0; i < total; i++)
            {
                auto.GennerateCountry();
                auto.GennerateProduct(lCate);
            }
            int result = await auto.SaveChangeAsync();
            var Output = new
            {
                Success = (result > 0),
                Total = result
            };
            return Json(Output);
        }
    }
}